In [3]:
import numpy as np
import pandas as pd

In [120]:
data=pd.read_excel("Mushroom.xlsx")
# data=pd.read_csv("/content/Social_Network_Ads.csv")

/Users/joestalin/opt/anaconda3/lib/python3.7/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


In [28]:
data.head()

Class Cap-shape Cap-surface Cap-color Bruises Odor Gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  Gill-spacing Gill-size Gill-color  ... Stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  Stalk-color-above-ring Stalk-color-below-ring Veil-type Veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  Ring-number Ring-type Spore-print-color Population Habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [29]:
data.describe()

Class Cap-shape Cap-surface Cap-color Bruises  Odor Gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       Gill-spacing Gill-size Gill-color  ... Stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       Stalk-color-above-ring Stalk-color-below-ring Veil-type Veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       Ring-number Ring-type Spore-print-color Population Habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [30]:
#drop user id column
# df=data.drop(['User ID'], axis=1)

In [31]:
data.head()

Class Cap-shape Cap-surface Cap-color Bruises Odor Gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  Gill-spacing Gill-size Gill-color  ... Stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  Stalk-color-above-ring Stalk-color-below-ring Veil-type Veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  Ring-number Ring-type Spore-print-color Population Habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [121]:
#converting categorical values of 'Gender' to numerical format
data['Class']=data['Class'].apply({'p':'1','e':'2'}.get)
# .cap-shape: bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s
data['Cap-shape']=data['Cap-shape'].apply({'b':'1','c':'2','x':'3','f':'4','k':'5','s':'6'}.get)
# 2. cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
data['Cap-surface']=data['Cap-surface'].apply({'f':'1','g':'2','y':'3','s':'4'}.get)
# 3. cap-color: brown=n,buff=b,cinnamon=c,gray=g,green=r, pink=p,purple=u,red=e,white=w,yellow=y
data['Cap-color']=data['Cap-color'].apply({'n':'1','b':'2','c':'3','g':'4','p':'5','u':'6','e':'7','w':'8','y':'9'}.get)
# 4. bruises?: bruises=t,no=f
data['Bruises']=data['Bruises'].apply({'t':'1','f':'2'}.get)
# 5. odor: almond=a,anise=l,creosote=c,fishy=y,foul=f, musty=m,none=n,pungent=p,spicy=s
data['Odor']=data['Class'].apply({'a':'1','l':'2','c':'3','y':'4','f':'5','m':'6','n':'7','p':'8','s':'9'}.get)
# 6. gill-attachment: attached=a,descending=d,free=f,notched=n
data['Gill-attachment']=data['Gill-attachment'].apply({'a':'1','d':'2','f':'3','n':'4'}.get)
# 7. gill-spacing: close=c,crowded=w,distant=d
data['Gill-spacing']=data['Gill-spacing'].apply({'c':'1','e':'2','d':'3'}.get)
# 8. gill-size: broad=b,narrow=n
data['Gill-size']=data['Gill-size'].apply({'p':'1','n':'2'}.get)
# 9. gill-color: black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e,
# white=w,yellow=y
data['Gill-color']=data['Gill-color'].apply({'k':'1','n':'2','b':'3','h':'4','g':'5','r':'6','o':'7','p':'8','u':'9','e':'10'}.get)
# 10. stalk-shape: enlarging=e,tapering=t
data['Stalk-shape']=data['Class'].apply({'e':'1','t':'2'}.get)
# 11. stalk-root: bulbous=b,club=c,cup=u,equal=e, rhizomorphs=z,rooted=r,missing=?
data['Stalk-root']=data['Class'].apply({'b':'1','c':'2','u':'3','e':'4','z':'5','r':'6','?':'7'}.get)
# 12. stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s
data['Stalk-surface-above-ring']=data['Stalk-surface-above-ring'].apply({'f':'1','y':'2','k':'3','s':'4'}.get)
# 13. stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s
data['Stalk-surface-below-ring']=data['Stalk-surface-below-ring'].apply({'f':'1','y':'2','k':'3','s':'4'}.get)
# 14. stalk-color-above-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
data['Stalk-color-above-ring']=data['Stalk-color-above-ring'].apply({'n':'1','b':'2','c':'3','g':'4','o':'5','p':'6','w':'7','e':'8','y':'9'}.get)
# 15. stalk-color-below-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
data['Stalk-color-below-ring']=data['Stalk-color-below-ring'].apply({'n':'1','b':'2','c':'3','g':'4','o':'5','p':'6','w':'7','e':'8','y':'9'}.get)
# 16. veil-type: partial=p,universal=u
data['Veil-type']=data['Veil-type'].apply({'p':'1','u':'2'}.get)
# 17. veil-color: brown=n,orange=o,white=w,yellow=y
data['Veil-color']=data['Veil-color'].apply({'n':'1','o':'2','w':'3','y':'4'}.get)
# 18. ring-number: none=n,one=o,two=t
data['Ring-number']=data['Ring-number'].apply({'n':'1','o':'2','t':'3'}.get)
# 19. ring-type: cobwebby=c,evanescent=e,flaring=f,large=l, none=n,pendant=p,sheathing=s,zone=z
data['Ring-type']=data['Ring-type'].apply({'c':'1','e':'2','f':'3','l':'4','n':'5','p':'6','s':'7','z':'8'}.get)
# 20. spore-print-color: black=k,brown=n,buff=b,chocolate=h,green=r, orange=o,purple=u,white=w,yellow=y
data['Spore-print-color']=data['Spore-print-color'].apply({'k':'1','n':'2','b':'3','h':'4','r':'5','o':'6','u':'7','w':'8','y':'9'}.get)
# 21. population: abundant=a,clustered=c,numerous=n, scattered=s,several=v,solitary=y
data['Population']=data['Population'].apply({'a':'1','c':'2','n':'3','s':'4','s':'5','y':'6'}.get)
# 22. habitat: grasses=g,leaves=l,meadows=m,paths=p, urban=u,waste=w,woods=d
data['Habitat']=data['Habitat'].apply({'p':'1','u':'2','w':'3','d':'4','l':'5','g':'6','m':'7'}.get)



In [ ]:
# #converting categorical values of 'Gender' to numerical format
# data['Class']=data['Class'].apply({'p':'poison','e':'edibility'}.get)
# # .cap-shape: bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s
# data['Cap-shape']=data['Cap-shape'].apply({'b':'bell','c':'conical','x':'convex','f':'flat','k':'knobbed','s':'sunken'}.get)
# # 2. cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
# data['Cap-surface']=data['Cap-surface'].apply({'f':'fibrous','g':'grooves','y':'scaly','s':'smooth'}.get)
# # 3. cap-color: brown=n,buff=b,cinnamon=c,gray=g,green=r, pink=p,purple=u,red=e,white=w,yellow=y
# data['Cap-color']=data['Cap-color'].apply({'n':'brown','b':'buff','c':'cinnamon','g':'gray','p':'pink','u':'purple','e':'red','w':'white','y':'yellow'}.get)
# # 4. bruises?: bruises=t,no=f
# data['Bruises']=data['Bruises'].apply({'t':'bruises','f':'no'}.get)
# # 5. odor: almond=a,anise=l,creosote=c,fishy=y,foul=f, musty=m,none=n,pungent=p,spicy=s
# data['Odor']=data['Class'].apply({'p':'poison','e':'edibility'}.get)
# # 6. gill-attachment: attached=a,descending=d,free=f,notched=n
# data['Gill-attachment']=data['Gill-attachment'].apply({'a':'attached','d':'descending','f':'free','n':'notched'}.get)
# # 7. gill-spacing: close=c,crowded=w,distant=d
# data['Gill-spacing']=data['Gill-spacing'].apply({'c':'close','e':'crowded','d':'distant'}.get)
# # 8. gill-size: broad=b,narrow=n
# data['Gill-size']=data['Gill-size'].apply({'p':'broad','n':'narrow'}.get)
# # 9. gill-color: black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e,
# # white=w,yellow=y
# data['Gill-color']=data['Gill-color'].apply({'k':'black','n':'brown','b':'buff','h':'chocolate','g':'gray','r':'green','o':'orange','p':'pink','u':'red','e':'purple'}.get)
# # 10. stalk-shape: enlarging=e,tapering=t
# data['Stalk-shape']=data['Class'].apply({'e':'enlarging','t':'tapering'}.get)
# # 11. stalk-root: bulbous=b,club=c,cup=u,equal=e, rhizomorphs=z,rooted=r,missing=?
# data['Stalk-root']=data['Class'].apply({'b':'bulbous','c':'club','u':'cup','e':'equal','z':'rhizomorphs','r':'rooted','?':'missing'}.get)
# # 12. stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s
# data['Stalk-surface-above-ring']=data['Stalk-surface-above-ring'].apply({'f':'fibrous','y':'scaly','k':'silky','s':'smooth'}.get)
# # 13. stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s
# data['Stalk-surface-below-ring']=data['Stalk-surface-below-ring'].apply({'f':'fibrous','y':'scaly','k':'silky','s':'smooth'}.get)
# # 14. stalk-color-above-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
# data['Stalk-color-above-ring']=data['Stalk-color-above-ring'].apply({'n':'brown','b':'buff','c':'cinnamon','g':'gray','o':'orange','p':'pink','w':'white','e':'red','y':'yellow'}.get)
# # 15. stalk-color-below-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
# data['Stalk-color-below-ring']=data['Stalk-color-below-ring'].apply({'n':'brown','b':'buff','c':'cinnamon','g':'gray','o':'orange','p':'pink','w':'white','e':'red','y':'yellow'}.get)
# # 16. veil-type: partial=p,universal=u
# data['Veil-type']=data['Veil-type'].apply({'p':'partial','u':'universal'}.get)
# # 17. veil-color: brown=n,orange=o,white=w,yellow=y
# data['Veil-color']=data['Veil-color'].apply({'n':'brown','o':'orange','w':'white','y':'yellow'}.get)
# # 18. ring-number: none=n,one=o,two=t
# data['Ring-number']=data['Ring-number'].apply({'n':'none','o':'one','t':'two'}.get)
# # 19. ring-type: cobwebby=c,evanescent=e,flaring=f,large=l, none=n,pendant=p,sheathing=s,zone=z
# data['Ring-type']=data['Ring-type'].apply({'c':'cobwebby','e':'evanescent','f':'flaring','l':'large','n':'none','p':'pendant','s':'sheathing','z':'zone'}.get)
# # 20. spore-print-color: black=k,brown=n,buff=b,chocolate=h,green=r, orange=o,purple=u,white=w,yellow=y
# data['Spore-print-color']=data['Spore-print-color'].apply({'k':'black','n':'brown','b':'buff','h':'chocolate','r':'green','o':'orange','u':'purple','w':'white','y':'yellow'}.get)
# # 21. population: abundant=a,clustered=c,numerous=n, scattered=s,several=v,solitary=y
# data['Population']=data['Population'].apply({'a':'abundant','c':'clustered','n':'numerous','s':'scattered','s':'several','y':'solitary'}.get)
# # 22. habitat: grasses=g,leaves=l,meadows=m,paths=p, urban=u,waste=w,woods=d
# data['Habitat']=data['Habitat'].apply({'p':'paths','u':'urban','w':'waste','d':'woods','l':'leaves','g':'grasses','m':'meadows'}.get)

In [124]:
data.head()

Class Cap-shape Cap-surface Cap-color Bruises  Odor Gill-attachment  \
0     1         3           4         1       1     0               3   
1     2         3           4         9       1     0               3   
2     2         1           4         8       1     0               3   
3     1         3           3         8       1     0               3   
4     2         3           4         4       2     0               3   

  Gill-spacing Gill-size Gill-color  ...  Stalk-surface-below-ring  \
0            1         2          1  ...                         4   
1            1         0          1  ...                         4   
2            1         0          2  ...                         4   
3            1         2          2  ...                         4   
4            0         0          1  ...                         4   

   Stalk-color-above-ring Stalk-color-below-ring Veil-type Veil-color  \
0                       7                      7         1          3   
1                       7                      7         1          3   
2                       7                      7         1          3   
3                       7                      7         1          3   
4                       7                      7         1          3   

  Ring-number Ring-type Spore-print-color Population Habitat  
0           2         6                 1          5       2  
1           2         6                 2          3       6  
2           2         6                 2          3       7  
3           2         6                 1          5       2  
4           2         2                 2          1       6  

[5 rows x 23 columns]

In [123]:
#divide the dataset into dependent and independent columns
data=data.fillna(0)
data=data.fillna(value=np.nan)
x=data.loc[:,data.columns!= 'Habitat']#independent in nature
y=data['Habitat']#dependent column

In [125]:
#split the data into training and testing set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [132]:
#importing KNN Classifier
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=3)

In [133]:
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [134]:
predictions=classifier.predict(x_test)

In [135]:
#accuracy computation
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [136]:
print(cm)

[[ 78   0   0  68  34  38   0]
 [  0  34   0   0   0  43   0]
 [  0   0  44   0   0   0   0]
 [125   1   0 426  31  38   0]
 [ 73   0   0  32  64   0   0]
 [ 71  39   0  27   0 260  39]
 [  0   0   0   0   0  55   5]]


In [137]:
print(ac)

0.5606153846153846
